CREATE TABLE IF NOT EXISTS CUSTOMERS (
    id int IDENTITY(5,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESSES (
    id int IDENTITY PRIMARY KEY,
    cep VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    customerId int,
    FOREIGN KEY (customerId) REFERENCES CUSTOMERS(id)
);